apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-production
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/AnteroPaivarinta/kubernetes-kurssi
        revision: main
        directories:
          - path: 4/4.9/overlays/production
  template:
    metadata:
      name: myapp-production
    spec:
      project: default
      source:
        repoURL: https://github.com/AnteroPaivarinta/kubernetes-kurssi
        targetRevision: main
        path: 4/4.9/overlays/production
      destination:
        server: https://kubernetes.default.svc
        namespace: myapp-production
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
