apiVersion: v1
kind: ConfigMap
metadata:
  name: exercises-config
  namespace: project
data:
  MESSAGE: "hello123"
  PORT: "3001"
  DATABASE_PORT: "5432"
  DATABASE_PASSWORD: "example"
  DATABASE: "postgres"
  DATABASE_HOST: "postgres-svc"
  DATABASE_USER: "postgres"
  NATS_URL: "nats-service:4222"
  DISCORD_TOKEN: "https://discordapp.com/api/webhooks/1466844511618727937/rLAr13-V7PLJgqAlxXQPpw3SGcWL1SKh6D6hDDK65x6xbGlc5_W0W7qjYNm9HkWMc2W7"
  information.txt: |
    this text is from file