apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - name: "front"
      port: 2345
      protocol: TCP
      targetPort: 5173
    - name: "rest"
      port: 2347
      protocol: TCP
      targetPort: 3001