apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3  
  failedJobsHistoryLimit: 1   
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: anteropaivarinta/cron-job
            env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: exercises-config          
                  key: DATABASE

            - name: POSTGRES_HOST 
              valueFrom:
                configMapKeyRef:
                  name: exercises-config          
                  key: DATABASE_HOST

            - name: POSTGRES_PORT 
              valueFrom:
                configMapKeyRef:
                  name: exercises-config          
                  key: DATABASE_PORT

            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: exercises-config          
                  key: DATABASE_PASSWORD

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: exercises-config          
                  key: DATABASE_USER
         
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
