apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-staging
  namespace: argocd          # yleens√§ ArgoCD namespace
spec:
  project: default
  source:
    repoURL: https://github.com/AnteroPaivarinta/kubernetes-kurssi
    path: 4/4.9/overlays/staging
    targetRevision: main    # deploy jokainen commit main branchiin
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-staging   # erillinen namespace stagingille
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
