apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: restart-rate
  namespace: exercises
spec:
  metrics:
  - name: restart-rate
    initialDelay: 5m
    successCondition: result < 2
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local
        query: |
          scalar(
            sum(kube_pod_container_status_restarts_total{namespace="exercises", container="ping-pong-app-update"}) -
            sum(kube_pod_container_status_restarts_total{namespace="exercises", container="ping-pong-app-update"} offset 2m)
          )