apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: namespace-cpu-usage
  namespace: exercises
spec:
  metrics:
  - name: cpu-usage
    interval: 30s
    initialDelay: 30s
    failureLimit: 1
    successCondition: result < 1.5
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local
        query: |
          sum(
            rate(container_cpu_usage_seconds_total{
              namespace="exercises",
              container!=""
            }[5m])
          )
